version: '3.9'

volumes:
  db_data:

services:
  front: #
    restart: always #whenever
    image: 'dhub.waag.org/ccn_front'
    ports:
      - '${FRONT_PORT}:80'
    container_name: '${COMPOSE_PROJECT_NAME}-front'
  cms:
    restart: always #whenever
    image: 'dhub.waag.org/ccn_cms'
    container_name: '${COMPOSE_PROJECT_NAME}-cms'
    ports:
      - '${CMS_PORT}:80'
    working_dir: /var/www
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db:3306/${COMPOSE_PROJECT_NAME}?serverVersion=10.10'
    volumes:
      - ./data/files:/var/www/drupal/web/sites/default/files
      - ./config/cms/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./config/cms/mail/msmtprc:/etc/msmtprc
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'mariadb:10.10'
    # server/port in Drupal settings.php must match
    container_name: '${COMPOSE_PROJECT_NAME}-db'
    restart: always
    environment:
      # N.B. database must no be publicly accessible
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${COMPOSE_PROJECT_NAME}'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
